AWSTemplateFormatVersion: 2010-09-09
Description: 'AWS Service Operator - Amazon S3 Bucket (aso-1otq2cgce)'
Parameters:
  Environment:
    Type: String
    Default: ""
    Description: Environment Name
  BucketName:
    Description: >-
      Must contain only lowercase letters, numbers, periods (.), and hyphens
      (-),Cannot end in numbers
    Type: String
  LoggingPrefix:
    Description: >-
      Must contain only lowercase letters, numbers, periods (.), and hyphens
      (-),Cannot end in numbers
    Type: String
    Default: Archive
  EnableLogging:
    Description: enable or discable S3 logging
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  EnableGlacierLifeCycle:
    Description: enable archiving to Glacier Storage
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  GlacierLifeCycleTransitionInDays:
    Description: Define how many days objects should exist before being moved to Glacier
    Type: String
    Default: '0'
  EnableVersioning:
    Description: enable versioning
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  LifeCyclePrefix:
    Description: >-
      Must contain only lowercase letters, numbers, periods (.), and hyphens
      (-),Cannot end in numbers
    Type: String
    Default: Archive
  BucketAccessControl:
    Description: define if the bucket can be accessed from public or private locations
    Type: String
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
      - LogDeliveryWrite
      - BucketOwnerRead
      - BucketOwnerFullControl
      - AwsExecRead
    Default: "Private"
  EnableStaticSite:
    Description: enable static site
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  StaticSiteIndex:
    Description: Index document for the S3 bucket static site
    Type: String
    Default: 'index.html'
  StaticSiteError:
    Description: Error document for the S3 bucket static site
    Type: String
    Default: "500.html"
Mappings: {}
Conditions:
  UseLogging: !Equals
    - !Ref EnableLogging
    - 'true'
  UseGlacierLifeCycle: !Equals
    - !Ref EnableGlacierLifeCycle
    - 'true'
  UseVersioning: !Equals
    - !Ref EnableVersioning
    - 'true'
  UseAsStaticSite: !Equals
    - !Ref EnableStaticSite
    - 'true'
Resources:
  S3bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['',[!Ref Environment,'-',!Ref 'BucketName']]
      AccessControl: !Ref BucketAccessControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      WebsiteConfiguration: !If
        - UseAsStaticSite
        - IndexDocument: !Ref StaticSiteIndex
          ErrorDocument: !Ref StaticSiteError
        - !Ref 'AWS::NoValue'
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: !Ref LifeCyclePrefix
            Status: Enabled
            ExpirationInDays: '365'
            Transitions:
              - TransitionInDays: !Ref GlacierLifeCycleTransitionInDays
                StorageClass: Glacier
      LoggingConfiguration: !If
        - UseLogging
        - DestinationBucketName: !Ref LoggingBucket
          LogFilePrefix: !Ref LoggingPrefix
        - !Ref 'AWS::NoValue'
      Tags:
        - Key: Environment
          Value: !Ref Environment
      VersioningConfiguration: !If
        - UseVersioning
        - Status: Enabled
        - !Ref 'AWS::NoValue'
    DeletionPolicy: Retain

  LoggingBucket:
    Condition: UseLogging
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Join ['',[!Ref Environment,'-',!Ref 'BucketName','logging']]

Outputs:
  BucketName:
    Value: !Ref S3bucket
    Description: Name of the sample Amazon S3 bucket.
  BucketArn:
    Value: !GetAtt
      - S3bucket
      - Arn
    Description: Name of the Amazon S3 bucket
  WebsiteURL:
    Value: !GetAtt
      - S3bucket
      - WebsiteURL
    Description: URL of the bucket that was created
